#!/bin/sh
# plandrop server starter — bring up a self-contained localhost plandrop server
# from the prebuilt GHCR images. No domain, DNS, or TLS proxy required.
#
# Canonical use:  curl -fsSL https://plandrop.dev/start.sh | sh
# Inspect first:  curl -fsSL https://plandrop.dev/start.sh -o start.sh
#                 (read it) then: sh start.sh
# Also runnable as `npx plandrop server`.
#
# It installs nothing on the host: Docker + Compose must already be present, or
# it says so and stops. Everything it writes lands in the current directory
# (compose file, .env, data/), and it is re-runnable — an existing .env or
# compose file is kept, then `pull` + `up -d` refresh the stack. The stack
# tracks the `latest` images; set PLANDROP_VERSION in .env to pin a release.
set -eu

# Where the ready-to-run compose file comes from. compose.proxy.yml is the
# self-contained variant: it bundles its own front proxy so one localhost port
# serves both the control entrypoint and the *.localhost tenant hosts.
PLANDROP_COMPOSE_URL="${PLANDROP_COMPOSE_URL:-https://raw.githubusercontent.com/Xalior/plandrop/main/compose.proxy.yml}"
COMPOSE_FILE_NAME="compose.proxy.yml"

fail() {
  echo "error: $*" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || fail "Docker is not installed (or not on PATH).
plandrop's server runs as Docker containers, and this script never installs
Docker for you. Install it first — https://docs.docker.com/get-docker/ —
then re-run this script."

docker compose version >/dev/null 2>&1 || fail "Docker is present but the Compose plugin is not.
Install Docker Compose v2 (the \`docker compose\` plugin) —
https://docs.docker.com/compose/install/ — then re-run this script."

# Fetch the compose file; an existing one is kept so local edits survive.
if [ ! -f "$COMPOSE_FILE_NAME" ]; then
  echo "fetching $COMPOSE_FILE_NAME ..."
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$PLANDROP_COMPOSE_URL" -o "$COMPOSE_FILE_NAME"
  elif command -v wget >/dev/null 2>&1; then
    wget -q "$PLANDROP_COMPOSE_URL" -O "$COMPOSE_FILE_NAME"
  else
    fail "neither curl nor wget is available to fetch $PLANDROP_COMPOSE_URL"
  fi
fi

# Write a localhost-defaults .env if none exists; yours is never overwritten.
# See .env.example in the repo for the documented reference of every setting.
if [ ! -f .env ]; then
  echo "writing .env (localhost defaults) ..."
  cat > .env <<EOF
# plandrop server configuration — generated by start.sh; edit freely.
# Reference: https://github.com/Xalior/plandrop/blob/main/.env.example
COMPOSE_FILE=$COMPOSE_FILE_NAME

# Bind to loopback: the server is reachable from this machine only.
PLANDROP_BIND=127.0.0.1

# The single public port (the bundled proxy) and the internal service ports.
PLANDROP_PROXY_PORT=8083
PLANDROP_PROXY_DOMAIN=localhost
PLANDROP_APACHE_PORT=8080
PLANDROP_INGRESS_PORT=8082

# Runtime data (per-tenant content + credentials) and operator templates.
PLANDROP_DATA=./data
PLANDROP_USER_TEMPLATES=./user-templates

# Files the stack writes are owned by you.
PLANDROP_UID=$(id -u)
PLANDROP_GID=$(id -g)

# The stack tracks the latest release; uncomment to pin one instead.
# PLANDROP_VERSION=0.3.0
EOF
fi

mkdir -p data/hosts data/auth user-templates

echo "pulling images ..."
docker compose -f "$COMPOSE_FILE_NAME" pull
docker compose -f "$COMPOSE_FILE_NAME" up -d

# Report the URL the stack actually bound: an existing .env may carry its own
# port/domain, and the environment overrides both (dotenv semantics: the last
# assignment in the file wins).
env_get() {
  if [ -f .env ]; then
    grep -E "^${1}=" .env | tail -n 1 | cut -d= -f2- || true
  fi
}
PROXY_PORT="${PLANDROP_PROXY_PORT:-$(env_get PLANDROP_PROXY_PORT)}"
PROXY_PORT="${PROXY_PORT:-8083}"
PROXY_DOMAIN="${PLANDROP_PROXY_DOMAIN:-$(env_get PLANDROP_PROXY_DOMAIN)}"
PROXY_DOMAIN="${PROXY_DOMAIN:-localhost}"

echo ""
echo "plandrop server is up: http://${PROXY_DOMAIN}:${PROXY_PORT}"
echo ""
echo "Next steps:"
echo "  npx plandrop init --domain http://${PROXY_DOMAIN}:${PROXY_PORT}"
echo "  npx plandrop create            # mint a host"
echo "  npx plandrop newdoc plan.html  # scaffold a document"
echo "  npx plandrop upload plan.html  # publish it"
echo ""
echo "Documents publish at http://<host-label>.${PROXY_DOMAIN}:${PROXY_PORT}/"
echo "(*.localhost resolves to loopback on modern OSes.)"
